version: "3.8"
services:
  server:
    container_name: server
    restart: always
    build: .
    ports:
      - ${PORT}:${PORT}
    depends_on:
      - db
    stdin_open: true
    tty: true

  db:
    container_name: db
    image: postgres
    ports:
      - 5433:${DB_PORT}
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}

volumes:
  pgdata: