version: "3.8"
services:
  db:
    image: postgres:14.6
    restart: always
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=redPandaReviews
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  server:
    build: .
    depends_on:
      - db
    environment:
      -
    ports:
      - "3000:3000"
